[envs.default]
dependencies = [
  "coverage[toml]",
  "pytest"
]
[envs.default.scripts]
test = "pytest {args:test}"
test-cov = "coverage run -m pytest {args:test}"
cov-report = [
  "- coverage combine",
  "coverage report --show-missing",
]
cov = [
  "test-cov",
  "cov-report",
]

[[envs.all.matrix]]
python = ["3.11"]

[envs.lint]
detached = true
dependencies = [
  "black>=22.10.0",
  "mypy>=0.991",
  "ruff>=0.0.166",
]
[envs.lint.scripts]
typing = "mypy --install-types --non-interactive {args: hdrbg }"
style = [
  "ruff check {args:hdrbg}",
  "black --check --diff {args:hdrbg}",
]
fmt = [
  "black {args:hdrbg}",
  "ruff check --fix {args:hdrbg}",
  "style",
]
all = [
  "style",
  "typing",
]
